const {Schema, model} = require("../db/connection");
require("dotenv").config()

const CivilServantLoanSchema = new Schema({
  fullName: { type: String },
  date: {type: Date, default:Date.now },
  dob: { type: String },
  idNumber: { type: String },
  nationality: { type: String },
  gender: { type: String },
  position: { type: String },
  grossIncome: { type : String},
  netIncome: { type : String},
  maritalStatus: { type: String },
  phoneNumber: { type: String },
  email: { type: String },
  ecNumber: { type: String },
  addressStatus: { type: String },
  address: { type: String },
  timeAtAddress: { type: String },
  dependants: { type: String },
  employer: { type: String },
  employerAddress: { type: String },
  employerContactNumber: { type: String },
  employerEmail: { type: String },
  periodWithEmployer: { type: String },
  nextOfKin: { type: String },
  nextOfKinAddress: { type: String },
  nextOfKinPhone: { type: String },
  relationship: { type: String },
  bankName: { type: String },
  accountNumber: { type: String },
  branchName: { type: String },
  loanAmount: { type: Number },
  loanTenure: { type: Number },

  status: { type: String, enum: ['pending', 'approved', 'denied'], default: 'pending' },
  approvedAmount: { type: Number },
  returnTenure: { type: Number },
  totalAmountToReturn: { type: Number },
  monthlyInstallment: { type: Number },
});

const NonCivilServantLoanSchema = new Schema({
  firstName: { type: String, required: true },
  date: {type: Date, default:Date.now },
  lastName: { type: String, required: true },
  dob: { type: String },
  idNumber: { type: String, required: true },
  nationality: { type: String, required: true },
  gender: { type: String, required: true },
  maritalStatus: { type: String, required: true },
  phoneNumber: { type: String, required: true },
  email: { type: String, required: true },
  ecNumber: { type: String, required: true },
  addressStatus: { type: String, required: true },
  address: { type: String, required: true },
  timeAtAddress: { type: Number, required: true },
  dependants: { type: Number, required: true },
  employer: { type: String, required: true },
  employerAddress: { type: String, required: true },
  employerContactNumber: { type: String, required: true },
  employerEmail: { type: String, required: true },
  periodWithEmployer: { type: Number, required: true },
  nextOfKin: { type: String, required: true },
  nextOfKinAddress: { type: String, required: true },
  nextOfKinPhone: { type: String, required: true },
  relationship: { type: String, required: true },
  bankName: { type: String, required: true },
  accountNumber: { type: String, required: true },
  branchName: { type: String, required: true },
  loanAmount: { type: Number, required: true },
  loanTenure: { type: Number, required: true },
  
  status: { type: String, enum: ['pending', 'approved', 'denied'], default: 'pending' },
  approvedAmount: { type: Number },
  returnTenure: { type: Number },
  totalAmountToReturn: { type: Number },
  monthlyInstallment: { type: Number },
});

const GovernmentPensionerLoanSchema = new Schema({
  fullName: { type: String, required: true },
  date: {type: Date, default:Date.now },
  
  dob: { type: Date, required: true },
  idNumber: { type: String, required: true },
  nationality: { type: String, required: true },
  gender: { type: String, required: true },
  maritalStatus: { type: String, required: true },
  phoneNumber: { type: String, required: true },
  email: { type: String, required: true },
  ecNumber: { type: String, required: true },
  addressStatus: { type: String, required: true },
  address: { type: String, required: true },
  timeAtAddress: { type: Number, required: true },
  dependants: { type: Number, required: true },
  employer: { type: String, required: true },
  employerAddress: { type: String, required: true },
  employerContactNumber: { type: String, required: true },
  employerEmail: { type: String, required: true },
  periodWithEmployer: { type: Number, required: true },
  nextOfKin: { type: String, required: true },
  nextOfKinAddress: { type: String, required: true },
  nextOfKinPhone: { type: String, required: true },
  relationship: { type: String, required: true },
  bankName: { type: String, required: true },
  accountNumber: { type: String, required: true },
  branchName: { type: String, required: true },
  loanAmount: { type: Number, required: true },
  loanTenure: { type: Number, required: true },
  
  status: { type: String, enum: ['pending', 'approved', 'denied'], default: 'pending' },
  approvedAmount: { type: Number },
  returnTenure: { type: Number },
  totalAmountToReturn: { type: Number },
  monthlyInstallment: { type: Number },
});

module.exports = {
  CivilServantLoan: model("CivilServantLoan", CivilServantLoanSchema),
  NonCivilServantLoan: model("NonCivilServantLoan", NonCivilServantLoanSchema),
  GovernmentPensionerLoan: model("GovernmentPensionerLoan", GovernmentPensionerLoanSchema),
};


module.exports = {
  CivilServantLoan: model("CivilServantLoan", CivilServantLoanSchema),
  NonCivilServantLoan: model("NonCivilServantLoan", NonCivilServantLoanSchema),
  GovernmentPensionerLoan: model("GovernmentPensionerLoan", GovernmentPensionerLoanSchema)
}
