require ("dotenv").config()
const {Schema, model} = require("../db/connection")

const LoanApplicationSchema = new Schema({
    dateOfApplication: String,
    name: String,
    middleName: String,
    surname: String,
    dob: String,
    id: String,
    nationality: String,
    gender: String,
    maritalStatus: String,
    phoneNumber: String,
    email: String,
    accommodation: String,
    loanPurpose: String,
    street: String,
    town: String,
    city: String,
    country: String,
    landlord: String,
    landlordContactNumber: String,
    durationOfStay: Number,
    dependents: Number,
    employer: String,
    employerAddress: String,
    employerPhone: String,
    employerEmail: String,
    periodOfEmployment: String,
    ecNumber: String,
    employmentStatus: String,
    position: String,
    grossIncome: String,
    netIncome: String,
    nextOfKinName: String,
    nextOfKinAddress: String,
    nextOfKinContact: String,
    nextOfKinRelationship: String,
    businessName: String,
    areaOfOperation: String,
    businessNature: String,
    durationOfOperation: String,
    amount: Number,
    tenure: Number,
    bank: String,
    bankBranch: String,
    branchCode: String,
    accountNumber: String,
    guarantorName: String,
    guarantorID: String,
    guarantorAddress: String,
    guarantorContact: String,
});

const LoanApplication = model("LoanApplication", LoanApplicationSchema);
module.exports = LoanApplication;